name: Workflow for ros[kinetic] test
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ROS test
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action_ros_kinetic
