name: main_workflow
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_kinetic:
    name: build_in_kinetic
    runs-on: ubuntu-latest    
    steps:
    - run: pwd && ls && ls ../
    - run: cp /scripts/entrypoint.sh /actions/kinetic/entrypoint.sh
    - uses: actions/checkout@master
    - uses: ./actions/kinetic
      
  build_melodic:
    name: build_in_melodic
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/melodic
