name: main_workflow
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build_in_kinetic
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/kinetic
