name: main_workflow
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros-dist: [kinetic, melodic]

    steps:
    - name: build on ros dist ${{matrix.ros-dist}}
      uses: actions/checkout@master
    - run: cp scripts/entrypoint.sh actions/${{matrix.ros-dist}}/entrypoint.sh
    - uses: ./actions/${{matrix.ros-dist}}